---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: groq-secret
  namespace: staging-essi
spec:
  encryptedData:
    GROQ_API_KEY: AgAL+65SgqDvePrZ/NKPE9TUMS+n20WMQYuCin6Xs0jdGvQ4e36GP2rBVQSHMQTtqFyu56MCkzaXXFs4twPHpz/WZJfk5SHD08RazE0H5EdB6Tcx5ehgf+SjojeaUBa62wCSV1TAV0YCz89GA3vR90bn2zVpCe9z9DQiCg4ZBEorPwh7WBqSdmddnlBUepF4wHPSujFGds5C9VRuocSCmGn39azydki8D9HttQaDH3p/giP6qdC+E5ClG46sIyXMT1h3SiBJV292E9LQDVCGM18nYSLVs33++ZyKqfdNJRx7eav8UCwBE3w2+Q0q9zoS27NnoEJlK+qhL5y2Tj5E1fxWOjXpWZoKP3amOpzT1kcSHx+2Vwm8MLsVOkf8VhcxTtHSDiQoodMe3LBjxjtVNCWDJARHPLWkTX1/HptbDmpxX5PlEpDIrl1wUSlp47Pzh9CxRO88oMm8uNwLVTSUWpgGGlaa7Rqc45O7WxBSSyWqMNCdnn5HJbdmBfauc8lHFPQx2PGbGTBOlY2iUD1jadrBMaedbPwMRJXm3VSwghdUCTR+5ocIEXN26e3QKflSK6pZ67N8cdKMpr2kSq7eOafkHF+RIN1NhxpM3BreL39VVTD4XQihvh4WOdafExngbn5wCZaQRVDoV+D4bDVw8ZRX7SIJT1jnkh9WyZpF6JhgnR69vfylCcE8yRYI1GrT4IPJ6b8K0jGF1Cm77xiea8Eeae72a05RhnnAApAJeKXQ+wFSuWclrUlU/s42BUS+Lfg145ECn/QkgJrjIvhge4kxTru19yY=
  template:
    metadata:
      name: groq-secret
      namespace: staging-essi
