apiVersion: apps/v1
kind: Deployment
metadata:
  name: food-macro-api
  namespace: staging-essi
  labels:
    app: food-macro-api
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: food-macro-api
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: food-macro-api
    spec:
      containers:
        - name: food-macro-api
          image: ezbaa/food-macro-api:backend
          imagePullPolicy: Always
          resources: {}
          ports:
            - containerPort: 8080
              name: http
          env:
            - name: GROQ_API_KEY
              valueFrom:
                secretKeyRef:
                  name: groq-secret
                  key: GROQ_API_KEY
            - name: GITHUB_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: github-secret
                  key: GITHUB_CLIENT_ID
            - name: GITHUB_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: github-secret
                  key: GITHUB_CLIENT_SECRET
            - name: ALLOWED_USERS
              valueFrom:
                secretKeyRef:
                  name: github-secret
                  key: ALLOWED_USERS
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
