---
apiVersion: v1
kind: Service
metadata: 
  name: food-macro-frontend-svc
  namespace: production-essi
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: food-macro-frontend