---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: groq-secret
  namespace: production-essi
spec:
  encryptedData:
    GROQ_API_KEY: AgA3blK8noh2T86NfWL7GrouTRz36FJZAL2AkfMREHhDf77Su0bGBmKdtS/9bHW3rPKpYPUHJPeejPzxEwnqO546N3AkjPh5ymIXWzkz0m32Oi8w2wJNcQpGrojC7KK6RPISWfVke+SUQ9VuyFHCpRpsfxObLZPZCwD5uINegTDj4zAI7NBfM/qwZgxlnHnC0FR0vAsCr170y1drFBV/wq9xhnK5RcmbA6xxd15dXoIN+epQX/3SZjjd7v1pdcgdaJEYMANrasBPnbwOcwA4B9yeX5gAHkrMKHNSz/ck1xOPsigKZrtW/+I3EmoWpwg8qzZ7Hc1I5D2ToEJin4gH950zqwS+i5FYlg6MTi2wtu6aB9kM3i+q3NFJ8GnkDCuhkb6ZeFVwzwmgLOZ02NgYObtLqDPAHC61MXyGvF20PDMoQK5hwh/BB98QNQGIqbW7kEVZfkKXtOFZq3XK7J/WH6eV/VNghgdiwLWB9FToz1mNXQpkx3UcwBSl67zWeDwHBcuvZI/s/S9AsZuOWOVHYG/U7ueVQwGd3ReBCbeip2ZEJziXElazI3ki/jHxcgUBlMr+8pVG50SBeuIu3SruRv0YY31mSnikyisSLKsVviK90ZWIFI7C2/0hutQIT7o8+Fl5uTgEYTT5tlLyWa+WPFqhRaBCYVW47h4RE8N8sg8EF/K/zKKy5t9NeTyGWcmlkXrto5wzfF/qtZzUWwWF+kGLpkisznupr7FIyJWWxuQZ8YDdSalgtL9KVufeY7sMtKeVOfHoPJmgZw==
  template:
    metadata:
      name: groq-secret
      namespace: production-essi
