---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: groq-secret
  namespace: staging-essi
spec:
  encryptedData:
    GROQ_API_KEY: AgBBqOmeWY4PSb4kBykcMfbD4nL7atHXYEMU6JWfh+MykqsWmF5r9WdlfBU00BHXgmmDluRzJN/OlSJZaZzoh/fy9EWIfKbasGB437Mgtlg8NxAD/iuxhANVSFI5wNMzjycur25DTcZPNaultNI0Y6BLg9riCim1gB6u1OcTINz8ZIj8LvvW1l2vyhxm5M9Cxo8KOqIGaQSvgrVUAIQAQuwZXEMrSdXCe8KMbsKIxCa0wuZc7JRYAkAZhT5lrqDRyUS0FW0BOmLdtfgBS4P4cqoRjyxaOIq8tQEdP5FZOiDc/SWLjwYZmSjvjUlryt1G78pOu/GzHMDqsYQrNiDXQdaYlx5v+Z/vjVN/28DdsMuvs9w/pwEk1j5SdS8DdlnNJaKnrKiNkPFYi0LfXFxF4a5YhhiJIYw/vlx3+XdjD9K3Ivm9hP08UI0sMOUEM6I6sQ0ZaOuLHRQ7GnKU+QPgGaDD3h4Kqmh3bI2mn//cLiGuS3cj/jzjVnN+khfsfYuWhoStO6pXiIIKdsj8cyTjXjYjw9Ef6LRvfW9hCfXHXEa2DbePvfrT6dUhoD8Ijs1HFcYZHToY+sD+uOSv/qx69XX7pLDMXzrvLxPBHZqUVQIYRd91wOEnZIbS9YfZlb2544y2J7X1hJtK2CYK09G+YVpgV7h5H6qbCByV4V3kja374f2m4MgyUZWUxWJSx36UOo0AuiHWXitskLiMUyJzOjp/hAjiLo7sRqKTS5FUFDX6TKRQgXgmolhh+7dNDDdpo92uLs0zv1WXiQ==
  template:
    metadata:
      name: groq-secret
      namespace: staging-essi