---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: groq-secret
  namespace: production-essi
spec:
  encryptedData:
    GROQ_API_KEY: AgCIQFFSLu/hYZBY5O4AWYAml8RaD+qtaKtkHMm99Qtplp6RrchYWnYadnIQc27zmG7Byz4kFyCA7XmOgI/3L/eb2fHPricQ2D+clTBFkt6Lp1D5wtK2xnQMjCVJ2BvXZC7lS+v6kAFiK0ztEvAKph6KRGKnfytGNkJ4lMyI4WkJHOsdvUIrO0XGME9LwC68EKY8SlqfUu5VmL9V993wycplSVPzbw41sGd9hvHnd79FqBAlV8OjvHdE0MEvAcui2qIg5msn/JP98Q8GZGWZanD2R3QN49zJRgp+Zwh4l2c/Z7pNIlS3jiUGoaqlQ4VyDTvMb+rxz8xnvduHrJcq6yrudWC4Te3OO18Pp0et3DuKkyH+nlrGNeUVFrQ7nNEE2mITgsBdgEyH5E9sbCapUZzqN2qhSHIn4nITrGKu5fFURkUtHwjFeBecBCbNMV+sAKjtquLl5qLsVlEMB7PGIcjUvUq/OXPwDBF/+RPFa349UczN9ErvG35ETAVlw3GD1noWtzy2iAOkK4ijJ725ATV+yASnHHzeUkssnY8bRVBAxkbFSHcfmiPxqiZuHz8Fe9xGFXavKZIjsNrJ8PNTISIVTe/UVRc3/h2hfv80PHxss2sI/jEhonYfgevAvjzFllqfi9BrnPE0VjFBgiNh/rTlXbURk/Ssjkiyb3xs150EzymuNG2Mv7jy/XBDu4/BLGzYA4VMNBMBz8hq3/6rw9JiqRHJYtNTZRmN/mQ5DI96hvKDFgHRJ8dyfS6RwtqwAOCpcl/mHTthXA==
  template:
    metadata:
      name: groq-secret
      namespace: production-essi
